import { 
  Baby, Banknote, BookText, Backpack, Building2, Bus, Car, Coffee, 
  Coins, Droplets, Flame, Fuel, Gift, Globe, Handshake, HelpCircle, 
  Home, Lightbulb, Milk, PartyPopper, Pill, Scissors, ShoppingCart, 
  Smartphone, Stethoscope, Utensils, Zap, Carrot, Salad, Smile, User, Wrench,
  Brush, Shirt
} from 'lucide-react';

export const CATEGORIES = [
  { id: "vegetables", icon: Carrot, emoji: "🥦", label: "Vegetables", bg: "rgba(232, 245, 233, 0.6)", group: "daily" },
  { id: "milk", icon: Milk, emoji: "🥛", label: "Milk / Dairy", bg: "rgba(243, 248, 255, 0.6)", group: "daily" },
  { id: "kirana", icon: ShoppingCart, emoji: "🛒", label: "Kirana Store", bg: "rgba(255, 248, 225, 0.6)", group: "daily" },
  { id: "food", icon: Utensils, emoji: "🍽️", label: "Hotel / Food", bg: "rgba(255, 240, 224, 0.6)", group: "daily" },
  { id: "chai", icon: Coffee, emoji: "☕", label: "Chai / Snacks", bg: "rgba(255, 243, 224, 0.6)", group: "daily" },
  { id: "cooking_gas", icon: Flame, emoji: "🔥", label: "Cooking Gas", bg: "rgba(255, 235, 238, 0.6)", group: "daily" },
  { id: "medicine", icon: Pill, emoji: "💊", label: "Medicine", bg: "rgba(232, 245, 233, 0.6)", group: "health" },
  { id: "doctor", icon: Building2, emoji: "🏥", label: "Doctor", bg: "rgba(252, 228, 236, 0.6)", group: "health" },
  { id: "lab_test", icon: Stethoscope, emoji: "🩺", label: "Lab Test", bg: "rgba(243, 229, 245, 0.6)", group: "health" },
  { id: "auto", icon: Car, emoji: "🛺", label: "Auto / Taxi", bg: "rgba(227, 242, 253, 0.6)", group: "transport" },
  { id: "bus_train", icon: Bus, emoji: "🚌", label: "Bus / Train", bg: "rgba(237, 231, 246, 0.6)", group: "transport" },
  { id: "petrol", icon: Fuel, emoji: "⛽", label: "Petrol / CNG", bg: "rgba(255, 249, 196, 0.6)", group: "transport" },
  { id: "electricity", icon: Lightbulb, emoji: "💡", label: "Electricity", bg: "rgba(255, 253, 231, 0.6)", group: "bills" },
  { id: "mobile", icon: Smartphone, emoji: "📱", label: "Mobile Recharge", bg: "rgba(232, 234, 246, 0.6)", group: "bills" },
  { id: "internet", icon: Globe, emoji: "🌐", label: "Internet / TV", bg: "rgba(224, 242, 241, 0.6)", group: "bills" },
  { id: "water", icon: Droplets, emoji: "💧", label: "Water Bill", bg: "rgba(225, 245, 254, 0.6)", group: "bills" },
  { id: "emi", icon: Banknote, emoji: "🏦", label: "EMI / Loan", bg: "rgba(255, 235, 238, 0.6)", group: "money" },
  { id: "lending", icon: Handshake, emoji: "🤝", label: "Lent Money", bg: "rgba(255, 243, 224, 0.6)", group: "money" },
  { id: "rent", icon: Home, emoji: "🏠", label: "House Rent", bg: "rgba(243, 229, 245, 0.6)", group: "money" },
  { id: "savings", icon: Coins, emoji: "🪙", label: "Savings / FD", bg: "rgba(249, 251, 231, 0.6)", group: "money" },
  { id: "school", icon: Backpack, emoji: "🎒", label: "School Fees", bg: "rgba(232, 245, 233, 0.6)", group: "education" },
  { id: "stationery", icon: BookText, emoji: "📚", label: "Books / Copies", bg: "rgba(255, 248, 225, 0.6)", group: "education" },
  { id: "kids", icon: Baby, emoji: "🧒", label: "Kids' Needs", bg: "rgba(255, 243, 224, 0.6)", group: "education" },
  { id: "repair", icon: Wrench, emoji: "🔧", label: "Repair / Plumber", bg: "rgba(236, 239, 241, 0.6)", group: "home" },
  { id: "household", icon: Brush, emoji: "🧹", label: "Home Items", bg: "rgba(245, 245, 245, 0.6)", group: "home" },
  { id: "clothing", icon: Shirt, emoji: "👗", label: "Clothes", bg: "rgba(252, 228, 236, 0.6)", group: "home" },
  { id: "temple", icon: Home, emoji: "🛕", label: "Temple / Pooja", bg: "rgba(255, 248, 225, 0.6)", group: "social" },
  { id: "function", icon: PartyPopper, emoji: "🎉", label: "Function / Event", bg: "rgba(252, 228, 236, 0.6)", group: "social" },
  { id: "gift", icon: Gift, emoji: "🎁", label: "Gift", bg: "rgba(243, 229, 245, 0.6)", group: "social" },
  { id: "salon", icon: Scissors, emoji: "💈", label: "Salon / Beauty", bg: "rgba(255, 240, 245, 0.6)", group: "social" },
  { id: "other", icon: HelpCircle, emoji: "❓", label: "Other", bg: "rgba(236, 239, 241, 0.6)", group: "other" },
];

export const CAT_GROUPS = [
  { key: "daily", label: "🥗 Daily Essentials" },
  { key: "health", label: "🏥 Health" },
  { key: "transport", label: "🚗 Getting Around" },
  { key: "bills", label: "📋 Bills & Recharges" },
  { key: "money", label: "💰 Money Matters" },
  { key: "education", label: "📚 Education & Kids" },
  { key: "home", label: "🏠 Home & Clothing" },
  { key: "social", label: "🎊 Social & Spiritual" },
  { key: "other", label: "❓ Other" },
];

export const COLORS = {
  primary: "#FF8C42",
  bg: "#FFF8F0",
  card: "rgba(255, 255, 255, 0.75)",
  text: "#1C0F00",
  muted: "#7C5C3E",
  hint: "#C4A882",
  soft: "rgba(255, 241, 230, 0.6)",
  border: "rgba(240, 213, 190, 0.4)",
  green: "#2E7D32",
  blue: "#1565C0",
  red: "#C62828",
  redBg: "rgba(255, 235, 238, 0.6)",
  greenBg: "rgba(232, 245, 233, 0.6)",
};
